339 implementierung sst management zuordnung
it-at-m/mobidam-sst-management pull request #10
Opened 2023-12-14 14:08 UTC by AnHo314

## Pull Request: 339 sst-management-zuordnung

### Description
Frontend: 
Adjust the RefArc-layout to mobidam, add a dummy schnittstellen overview and a dummy schnittstellen-detail view.
Further it now is possible to add persons to a zuordnung. The list of the persons with further information is shown in the detail view of each schnittstelle. SSO and IAM access is solved in another issue.

### Reference
https://jira.muenchen.de/browse/MDAS-339

Issues:

### Definition of Done
- [x] Acceptance criteria are met
- [x] Build/Test workflow has successfully finished
- [x] Release notes are complemented
- [x] Documentation is complemented (operator manual, system specification)
- [x] Frontend is locally smoke-tested
- [x] Side branches are deleted
- [x] Board is updated
- [x] Infrastructure is adjusted

2023-12-20 15:43 UTC, mirrodi requested changes

2023-12-20 15:43 UTC, mirrodi commented on docs/src/dokumentation/RELEASENOTES.md
> +- Frontend auf Mobidam angepasst
Kann man dann bisschen detaillierter angeben was genau?

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/apigateway/src/main/resources/application-local.yml
der ganze Inhalt kann in die `application.yml`

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/apigateway/src/main/resources/application.yml
> +      - routing
```suggestion
```

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/apigateway/src/main/resources/application.yml
> +        uri: http://localhost:39146/
rauslöschen oder auslagern in eine local/test-YML. @martind260 hast du eine Idee?

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/App.vue
> +                        :src="require('./assets/logo.png')"
gibt es mittlerweile ein anderes Logo?

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/api/ZuordnungService.ts
> +            if (response.status != 502) {
```suggestion
            if (response.status == 502) {
```
Warum wir hier auf ein ungleich geprüft? Müsste man nicht prüfen ob das 502 `Bad Gateway` zurückgekommen ist?

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +                    ></v-text-field>
Würde es hier Sinn machen hier die "Magic Numbers" (maxlength, minlength, ...) auszulagern und als Konstante immer wieder zu nutzen?

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +                                    :min="new Date().toISOString()"
Würde hier auch auslagern, sonst schwebt dieser Methodenaufruf hier so rum und man versteht nicht direkt warum das so überhaupt gemacht wird

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +                                    :min="new Date().toISOString()"
Gleiches Feedback wie oben

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +const maxLength = 255;
Hier wird maxLength definiert und im `template` wird auch maxlength gesetzt. Spricht für auslagern und an 1 Stelle verwalten

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +let schnittstelleID = useRouter().currentRoute.params.id;
Kann man nicht die `schnittstelleID` als Prop an das AddPersonDialog übergeben? Das Auslesen aus der Route ist nicht so elegant

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +});
```suggestion
const zuordnung= ref<Zuordnung>(new Zuordnung(""));
```

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +}
```suggestion
function resetZuordnung(): void {
    zuordnung.value = new Zuordnung("");
    form.value?.resetValidation();
}
```

2023-12-20 15:43 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/components/AddPersonDialog.vue
> +    background-color: #395b64;
Farben würde ich immer in ein CSS File auslagern sonst wird Design-Überarbeitung ziemlich schwer

2023-12-20 15:45 UTC, mirrodi requested changes

2023-12-20 15:45 UTC, mirrodi commented on mobidam-sst-management-frontend/frontend/src/views/MainView.vue
>                  </p>
Würde ich rauslöschen

2023-12-20 15:56 UTC, mirrodi commented
# Design
![image](https://github.com/it-at-m/mobidam-sst-management/assets/77114015/a80232bc-73f1-459c-b2bb-6ceb16252be3)
- [ ] Die Liste der Schnittstellen soll so breit sein wie das ganze Fenster

![image](https://github.com/it-at-m/mobidam-sst-management/assets/77114015/e96d9154-7e82-45ca-a521-a53c87608ace)
- [ ] Der Button für hinzufügen schaut ein bisschen "out-of-place" aus. Vielleicht woanders platzieren?
- [ ] Würde den Button ohne Schatten machen, entweder outlined oder block

![image](https://github.com/it-at-m/mobidam-sst-management/assets/77114015/776b3383-5862-49fb-954c-3dbf9f665d65)
- [ ] Der "Schließen"-Button soll mMn weg und vom Kreuz rechts oben ersetzt werden
- [ ] Falls ich das richtig verstanden habe ist die minLength 1, aber im Dialog wird die Länge von 0 bis 255 angezeigt
- [ ] Ich würde die 2 Felder "Gültig ab" und "Gültig bis" anders formatieren, weil sie jetzt durch die Linie wie Textfelder ausschauen. Vielleicht ein outlined statt underlined Feld (https://vuetifyjs.com/en/components/text-fields/#usage)

![image](https://github.com/it-at-m/mobidam-sst-management/assets/77114015/566e5abc-3122-4238-bd71-bce5a139b690)
- [ ] Kalender soll auf Deutsch sein

2023-12-27 15:37 UTC, mirrodi approved these changes

2024-01-03 13:43 UTC, AnHo314 commented
@mirrodi Danke für das Review + Korrektur

2024-01-08 09:20 UTC, merged