Mdas 594 api endpunkt fuer statusabfrage
it-at-m/mobidam-sst-management pull request #27
Opened 2024-02-26 06:50 UTC by martind260

---
name: Pull request template
about: Create a pull request to contribute to our software
title: ""
labels: ""
assignees: ""
---

## Pull Request

### Description

### Reference

Issues:

### Definition of Done
- [ ] Acceptance criteria are met
- [ ] Build/Test workflow has successfully finished
- [ ] Release notes are complemented
- [ ] Documentation is complemented (operator manual, system specification)
- [ ] Frontend is locally smoke-tested
- [ ] Side branches are deleted
- [ ] Board is updated
- [ ] Infrastructure is adjusted

2024-02-27 07:38 UTC, mirrodi requested changes

2024-02-27 07:38 UTC, mirrodi commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/rest/SchnittstelleController.java
> +    @GetMapping("{id}/status")
Bin mir unsicher, aber ist nicht die Konvention, dass die Path-Parameter als letztes kommen?
```suggestion
    @GetMapping("status/{id}")
```

2024-02-27 07:38 UTC, mirrodi commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/service/SchnittstelleService.java
> +        }
Dieser Block ist aus meiner Sicht überflüssig, da wir einen `GlobalExceptionHandler` für `IllegalArgumentException` haben, der automatisch einen `BAD_REQUEST` zurückschickt.

2024-02-27 07:38 UTC, mirrodi commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/service/SchnittstelleService.java
> +        return sst.map(schnittstelle -> new SchnittstelleGetStatusDTO(schnittstelle.getStatus().name()));
```suggestion
        return  schnittstelleRepository.findById(uuid).map(schnittstelle -> new SchnittstelleGetStatusDTO(schnittstelle.getStatus().name()));
```

2024-02-27 07:38 UTC, mirrodi commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/domain/dtos/SchnittstelleGetStatusDTO.java
> +}
Macht es Sinn hier nochmal die ID und/oder Namen zurückzugeben? Würde das die Umsetzung auf der anderen Seite erleichtern oder ist es überflüssig?

2024-02-27 11:53 UTC, martind260 commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/rest/SchnittstelleController.java
> +    @GetMapping("{id}/status")
@mirrodi Ich habe dazu keine Konvention gefunden. Wenn Du mir einen Link nennen kannst, schau ich mal drüber.

2024-02-27 11:55 UTC, martind260 commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/domain/dtos/SchnittstelleGetStatusDTO.java
> +}
@mirrodi Ich sehe da keinen Vorteil, die ID wird ja schon im Request hingeschickt und der Name ist gar nicht genau bekannt.

2024-02-27 12:02 UTC, mirrodi commented on mobidam-sst-management-backend/src/main/java/de/muenchen/mobidam/rest/SchnittstelleController.java
> +    @GetMapping("{id}/status")
Hab Query's und Path-Parameters verwechselt anscheinend. Müsste dann so passen wie es ist

2024-02-28 10:36 UTC, mirrodi approved these changes

2024-02-28 10:39 UTC, merged